### ISSUE TITLE
Remove old staff members

### ISSUE THREAD

**Issue by AnilMistry** [GSTT-CSC/csc-test-site#154] opened 2022-12-07 14:45 UTC
We need to remove Lucy Funnells entry from the current staff members.

Going forward should we maintains old member profiles or should they be fully removed. 

I think articles and blog entries, authored by staff who then leave, should remain on the website.

**Comment by hshuaib90** [comment] 2022-12-07 14:46
I think this is duplicate of #151 . Can you additional comments there please?

**Closed as not planned** 2022-12-07 14:46 UTC
